### ISSUE TITLE
HDC 安装报错

### ISSUE THREAD

**Issue by CYLlinmaian** [likuai2010/ClashMeta#10]
[Info]App install path:F:\ROOT\Harmony OS NEXT\clash-entry-default.hap, queuesize:0, msg:error: failed to install bundle. code:9568320 error: no signature file.
有办法把直接把签名放进去让小白直接使用hdc安装吗，目前直接安装会报错

**Comment by dandanvoice** [comment]
肯定没有办法，因为签名是需要到华为那边申请的，这种应用华为根本不可能给签名的。直接打包编译到手机才是正确的方法。

**Comment by jin123d** [comment]
自己编译到手机吧。签名是需要到华为申请的，除非你用openHarmony 的设备才可以直接用 hdc 来安装。

**Comment by zyy515** [comment]
@CYLlinmaian 你登录自己华为账户然后自动签名就行了，文件->工程结构->签名配置 勾选自动签名default和prod都要勾选。签名完成后就可以安装了。

**Comment by likuai2010** [comment]
安装器已发布
