### ISSUE TITLE
Next 70 下报错 RpcClient: onFailed code = 16000002

### ISSUE THREAD

**Issue by asmh1989** [likuai2010/ClashMeta#12]
如题, ClashVpnAbility type 手动修改可以编译成功, 但是运行的时候 connectServiceExtensionAbility 连接失败
code = 16000002   api 说是 Incorrect ability type. 
有办法解决嘛, 现在状态, 配置下载完成, 但是点击规则界面, 内容为空

**Comment by likuai2010** [comment]
麻烦截图看看

**Comment by asmh1989** [comment]
@likuai2010 我用autoInstall  安装你打包的版本也是 代理规则界面空白
![lADPJx8Z4VlURFvNCxzNBOw_1260_2844](https://github.com/user-attachments/assets/10894c90-c943-4dd9-83c2-c5333e652822)
![lADPD2eDb1gvxFzNCxzNBOw_1260_2844](https://github.com/user-attachments/assets/a8c1f301-c523-41d8-832f-c1d48969fd15)

**Comment by likuai2010** [comment]
看一下日志

**Comment by likuai2010** [comment]
这问题出现p系列机型，m系列正正常，

**Comment by likuai2010** [comment]
后续可能要换其他形式来切换节点，
