### ISSUE TITLE
稳定性不好

### ISSUE THREAD

**Issue by 000wbh000** [likuai2010/ClashMeta#14]
启动后建立链接，右上角通知栏会显示相应图标，这时是正常的；但经常会莫名其妙就断联，通知栏图标消失，同样的配置，别其他设备就不会这样。这样的断连总是频繁发生，有时甚至是一刷新、打开网页就断，几乎不可用的状态。
有时还出现已经停止，但梯子还挂着的bug

**Comment by wudz** [comment]
链接没多久就断联了，现在又改进吗？

**Comment by likuai2010** [comment]
等优化
