### ISSUE TITLE
关于鸿蒙next后台运行的问题反馈

### ISSUE THREAD

**Issue by 793001157** [likuai2010/ClashMeta#16]
目前我在使用的过程中，打开APP运行会出现VPN钥匙，但是后台大概1分钟左右，VPN就自己掉了。目前0.0.71版本的next没找到应用后台运行的设置。是需要APP自行修正吗？

**Comment by shunlongyang** [comment]
同样遇到了这个问题，还有测速的延时特别大，不知道为什么

**Comment by wudz** [comment]
在前台VPN也掉，是不是被系统底层给扫描到VPN开启，然后关闭？

**Comment by likuai2010** [comment]
api 不稳定， 需要优化

**Comment by 793001157** [comment]
> api 不稳定， 需要优化

了解。那么等待大佬公测版后优化~~
