### ISSUE TITLE
编译和运行闪退

### ISSUE THREAD

**Issue by Satthimar** [likuai2010/ClashMeta#2]
extensionAbilities里的type值不允许是vpn
![屏幕截图 2024-09-21 171303](https://github.com/user-attachments/assets/77c8c8a3-32f9-4a13-bea2-b5680089d3e8)

从url导入配置下载时闪退，编译器里看遇到了空指针，编译器的报错定位在napi_init.cpp里143行的fetchAndValid函数附近

在代理启动后点击主页面的日志会有文件不存在的弹窗

平板next0.66
api12 5.0.0.25

**Comment by likuai2010** [comment]
根据ide的提示，手动添加vpnType,

**Comment by ThxGodNovember** [comment]
> 根据ide的提示，手动添加vpnType,

能请问下如何添加吗 @likuai2010
