### ISSUE TITLE
运行时无法点进去代理，显示rpc服务启动失败

### ISSUE THREAD

**Issue by avengerdsf** [likuai2010/ClashMeta#26]
显示内容：rpc服务启动失败: RpcClient:onFailed: code:16000002
![微信图片_2024-11-05_132308_650](https://github.com/user-attachments/assets/4ac85ce9-e0fc-4e51-994b-dcbf7a00f1ae)

**Comment by avengerdsf** [comment]
机型：pura70p 系统5.0.0.102(SP6C00E102R5P9patch01)

**Comment by likuai2010** [comment]
p系列不支持ipc, 请等华为官方修复

**Comment by avengerdsf** [comment]
好的好的，谢谢
