### ISSUE TITLE
go核心编译失败

### ISSUE THREAD

**Issue by wudz** [likuai2010/ClashMeta#27]
脚本目录下无法生成myapp.so,提示失败

PS D:\Test\HarmonyOSNext\ClashMeta-master\entry\src\main\golang> .\build.ps1
github.com/metacubex/mihomo/common/singleflight
# github.com/metacubex/mihomo/common/singleflight
..\..\foss\golang\clash\common\singleflight\singleflight.go:15:2: "runtime" imported and not used
runtime/cgo
net
failed

**Comment by likuai2010** [comment]
手动删除 runtime
