### ISSUE TITLE
根据URL下载完配置文件并保存成功后，依旧无法访问外网

### ISSUE THREAD

**Issue by TutuTang** [likuai2010/ClashMeta#31]
URL可在pc和另一台Android设备上正常使用，但在clashMeta上不行；正常出现钥匙图标，日志无报错信息

**Comment by angduxio** [comment]
我也是，其他人没遇到吗

**Comment by kevinGan** [comment]
+1

**Comment by quancs** [comment]
+1

**Comment by kevinGan** [comment]
> +1

我用的是vmess + ws + tls 模式，端口443的，跟模式会有关系么？

同样的配置，在MacOS下是正常用的（因为是订阅的同一个URL）

**Comment by kevinGan** [comment]
> > +1
> 
> 我用的是vmess + ws + tls 模式，端口443的，跟模式会有关系么？
> 
> 同样的配置，在MacOS下是正常用的（因为是订阅的同一个URL）

测试了一下，原因跟另外一个issue里说的一样
https://github.com/likuai2010/ClashMeta/issues/28

在5G网下，WLAN需要开着，如果WLAN关了会导致 proxy失效，把WLAN开着（但是没连任何ssid），5G下就能爬梯了
