### ISSUE TITLE
1.5.4开启转发后点“代理规则模式”按钮闪退

### ISSUE THREAD

**Issue by wpczoe** [likuai2010/ClashMeta#34]
RT

**Comment by BG7ZAG** [comment]
是不是节点过多？我试了少节点能正常进入，一旦节点过多就闪退

**Comment by kevinGan** [comment]
> 是不是节点过多？我试了少节点能正常进入，一旦节点过多就闪退

今天更了1.5.6修复这个了

![image](https://github.com/user-attachments/assets/137798ea-019f-4045-98cb-d0eb67d45c83)

**Comment by wpczoe** [comment]
1.5.6更新后不闪退了，但是也不显示规则组。
