### ISSUE TITLE
更新最新5.0.0.113 SP8后无法打开app

### ISSUE THREAD

**Issue by falser101** [likuai2010/ClashMeta#44]
更新前可以打开运行

**Comment by kevinGan** [comment]
70rs 5.0.0.113 SP8 正常使用

**Comment by liuyanhit** [comment]
昨天更新后，今天打不打开，更新前后显示版本都显示为5.0.0.112 SP1 
型号pura 70 pro+

**Comment by falser101** [comment]
> 70rs 5.0.0.113 SP8 正常使用

原来是不能关闭开发者选项，重新打开后就行了
