### ISSUE TITLE
新增配置闪退

### ISSUE THREAD

**Issue by zhumyww** [likuai2010/ClashMeta#5]
配置-添加配置，点击保存，闪退

**Comment by likuai2010** [comment]
需要编译Golang核心

**Comment by zhumyww** [comment]
> 需要编译Golang核心

请问可以再指导下吗，怎么编译Golang核心

**Comment by likuai2010** [comment]
项目里有build.ps1

**Comment by zhumyww** [comment]
> 项目里有build.ps1
这个怎么使用啊

**Comment by zhumyww** [comment]
> 项目里有build.ps1

这个怎么使用呢

**Comment by zhumyww** [comment]
> 项目里有build.ps1

报错：
PS Z:\ClashMeta\entry\src\main\golang> .\build.ps1
cfa/native/common
cfa/blob
runtime/cgo
os/user
net
cfa/native/platform
cfa/native/proxy
cfa/native/tun
cfa/native/app
cfa/native/tunnel
# cfa/native/proxy
native\proxy\http.go:21:23: listener.Listener undefined (type *"github.com/metacubex/mihomo/listener/http".Listener has no field or method Listener, but does have unexported field listener)
# cfa/native/app
native\app\dns.go:17:6: undefined: dns.UpdateSystemDNS
native\app\dns.go:18:6: undefined: dns.FlushCacheWithDefaultResolver
# cfa/native/tun
native\tun\dns.go:26:16: undefined: dns.ServeDNSWithDefaultServer
# cfa/native/tunnel
native\tunnel\connectivity.go:22:58: undefined: outboundgroup.ProxyGroup
native\tunnel\geoip.go:12:8: undefined: mmdb.InstallOverride
native\tunnel\geoip.go:21:7: undefined: mmdb.InstallOverride
native\tunnel\providers.go:50:20: undefined: P.UpdatableProvider
native\tunnel\proxies.go:64:84: undefined: outboundgroup.ProxyGroup
native\tunnel\proxies.go:92:58: undefined: outboundgroup.ProxyGroup
native\tunnel\proxies.go:141:58: undefined: outboundgroup.ProxyGroup
native\tunnel\proxies.go:175:63: undefined: outboundgroup.ProxyGroup
native\tunnel\proxies.go:213:65: undefined: outboundgroup.ProxyGroup
native\tunnel\statistic.go:16:34: statistic.DefaultManager.Total undefined (type *statistic.Manager has no field or method Total)
native\tunnel\statistic.go:16:34: too many errors
failed

**Comment by dugufei** [comment]
> 项目里有build.ps1

runtime/cgo
# runtime/cgo
gcc_android.c:6:10: fatal error: 'android/log.h' file not found

mac电脑上报这个错。我看环境变量里已经配置了ndk了呢

**Comment by dugufei** [comment]
`
runtime/cgo

 #runtime/cgo
gcc_android.c:6:10: fatal error: 'android/log.h' file not found
`
mac电脑上报这个错。我看环境变量里已经配置了ndk了呢

**Comment by summershrimp** [comment]
> ` runtime/cgo
> 
> #runtime/cgo gcc_android.c:6:10: fatal error: 'android/log.h' file not found ` mac电脑上报这个错。我看环境变量里已经配置了ndk了呢

需要自己魔改一下cgo的代码

**Comment by dugufei** [comment]
> > ` runtime/cgo
> > #runtime/cgo gcc_android.c:6:10: fatal error: 'android/log.h' file not found ` mac电脑上报这个错。我看环境变量里已经配置了ndk了呢
> 
> 需要自己魔改一下cgo的代码

大佬能指导一下需要怎么改么

**Comment by Anti-ACustomers** [comment]
> > 项目里有build.ps1
> 
> 报错： PS Z:\ClashMeta\entry\src\main\golang> .\build.ps1 cfa/native/common cfa/blob runtime/cgo os/user net cfa/native/platform cfa/native/proxy cfa/native/tun cfa/native/app cfa/native/tunnel
> 
> # cfa/native/proxy
> native\proxy\http.go:21:23: listener.Listener undefined (type *"github.com/metacubex/mihomo/listener/http".Listener has no field or method Listener, but does have unexported field listener)
> 
> # cfa/native/app
> native\app\dns.go:17:6: undefined: dns.UpdateSystemDNS native\app\dns.go:18:6: undefined: dns.FlushCacheWithDefaultResolver
> 
> # cfa/native/tun
> native\tun\dns.go:26:16: undefined: dns.ServeDNSWithDefaultServer
> 
> # cfa/native/tunnel
> native\tunnel\connectivity.go:22:58: undefined: outboundgroup.ProxyGroup native\tunnel\geoip.go:12:8: undefined: mmdb.InstallOverride native\tunnel\geoip.go:21:7: undefined: mmdb.InstallOverride native\tunnel\providers.go:50:20: undefined: P.UpdatableProvider native\tunnel\proxies.go:64:84: undefined: outboundgroup.ProxyGroup native\tunnel\proxies.go:92:58: undefined: outboundgroup.ProxyGroup native\tunnel\proxies.go:141:58: undefined: outboundgroup.ProxyGroup native\tunnel\proxies.go:175:63: undefined: outboundgroup.ProxyGroup native\tunnel\proxies.go:213:65: undefined: outboundgroup.ProxyGroup native\tunnel\statistic.go:16:34: statistic.DefaultManager.Total undefined (type *statistic.Manager has no field or method Total) native\tunnel\statistic.go:16:34: too many errors failed

大佬，这个问题解决了吗

**Comment by zhumyww** [comment]
> > > 项目里有build.ps1
> 大佬，这个问题解决了吗
没有，魔改go代码超出能力范围了，呼叫大佬 @likuai2010

**Comment by summershrimp** [comment]
没啥难的 根据报错找到goroot里面对应的文件改改就行。。一共只需要改俩文件三行
如果这个都搞不定的话等别人共享测试链接装吧

**Comment by avengerdsf** [comment]
> 没啥难的 根据报错找到goroot里面对应的文件改改就行。。一共只需要改俩文件三行 如果这个都搞不定的话等别人共享测试链接装吧

同求，能不能指导一下

**Comment by summershrimp** [comment]
`$GOROOT/src/runtime/cgo/gcc_android.c`
删除 `#include <android/log.h>`
删除所有调用`__android_log_printf`的地方

`$GOROOT/src/net/cgo_resold.go`
修改`C.getnameinfo(sa, salen, (*C.char)(unsafe.Pointer(&b[0])), C.size_t(len(b)), nil, 0, C.NI_NAMEREQD)`
为`C.getnameinfo(sa, salen, (*C.char)(unsafe.Pointer(&b[0])), C.socklen_t(len(b)), nil, 0, C.NI_NAMEREQD)`

**Comment by ChangweiZhang** [comment]
大佬，根据你的回答修改了src目录下的文件还是报错。是有缓存吗？还是要用修改的src代码重新编译go的可执行文件？ @summershrimp
