### ISSUE TITLE
配置是不是有问题

### ISSUE THREAD

**Issue by 001SM** [likuai2010/ClashMeta#7]
> hvigor ERROR: Failed :entry:default@PreBuild... 
> hvigor ERROR: Schema validate failed.
	 Detail: Please check the following fields.
{
  instancePath: 'module.extensionAbilities[0].type',
  keyword: 'enum',
  params: {
    allowedValues: [
      'form',
      'workScheduler',
      'inputMethod',
      'service',
      'accessibility',
      'dataShare',
      'fileShare',
      'staticSubscriber',
      'wallpaper',
      'backup',
      'window',
      'enterpriseAdmin',
      'thumbnail',
      'preview',
      'print',
      'share',
      'push',
      'driver',
      'action',
      'adsService',
      'embeddedUI',
      'insightIntentUI',
      'autoFill/password',
      'hms/account',
      'appAccountAuthorization',
      'ads',
      'remoteNotification',
      'remoteLocation',
      'statusBarView',
      'voip',
      'accountLogout',
      'sysDialog/userAuth',
      'sysDialog/common',
      'sysDialog/atomicServicePanel',
      'sysDialog/power',
      'sysDialog/meetimeCall',
      'sysDialog/meetimeContact',
      'sysDialog/meetimeMessage',
      'sysDialog/print',
      'sysPicker/mediaControl',
      'sysPicker/share',
      'sysPicker/meetimeContact',
      'sysPicker/meetimeCallLog',
      'sysPicker/photoPicker',
      'sysPicker/appSelector',
      'sysPicker/navigation',
      'sysPicker/photoEditor',
      'photoEditor',
      'sysPicker/filePicker',
      'sysPicker/audioPicker',
      'sys/visualExtension',
      'sys/commonUI',
      'fileAccess',
      'autoFill/smart',
      'liveViewLockScreen',
      'recentPhoto'
    ]
  },
  message: 'must be equal to one of the allowed values',
  location: 'C:/Users/57357/Desktop/ClashMeta-master/entry/src/main/module.json5:46:22'
} 

> hvigor ERROR: BUILD FAILED in 199 ms 
提示要把    "extensionAbilities": [
      {
        "name": "ClashVpnAbility",
        "srcEntry": "./ets/ipc/ClashVpnAbility.ets",
        "type": "vpn"
      },中的“vpn”换掉

**Comment by likuai2010** [comment]
![Uploading image.png…]()
手动添加 vpn 到allowedValues

**Comment by starslightbright** [comment]
> > hvigor ERROR: Failed :entry:default@PreBuild...
> > hvigor ERROR: Schema validate failed.
> > Detail: Please check the following fields.
> > {
> > instancePath: 'module.extensionAbilities[0].type',
> > keyword: 'enum',
> > params: {
> > allowedValues: [
> > 'form',
> > 'workScheduler',
> > 'inputMethod',
> > 'service',
> > 'accessibility',
> > 'dataShare',
> > 'fileShare',
> > 'staticSubscriber',
> > 'wallpaper',
> > 'backup',
> > 'window',
> > 'enterpriseAdmin',
> > 'thumbnail',
> > 'preview',
> > 'print',
> > 'share',
> > 'push',
> > 'driver',
> > 'action',
> > 'adsService',
> > 'embeddedUI',
> > 'insightIntentUI',
> > 'autoFill/password',
> > 'hms/account',
> > 'appAccountAuthorization',
> > 'ads',
> > 'remoteNotification',
> > 'remoteLocation',
> > 'statusBarView',
> > 'voip',
> > 'accountLogout',
> > 'sysDialog/userAuth',
> > 'sysDialog/common',
> > 'sysDialog/atomicServicePanel',
> > 'sysDialog/power',
> > 'sysDialog/meetimeCall',
> > 'sysDialog/meetimeContact',
> > 'sysDialog/meetimeMessage',
> > 'sysDialog/print',
> > 'sysPicker/mediaControl',
> > 'sysPicker/share',
> > 'sysPicker/meetimeContact',
> > 'sysPicker/meetimeCallLog',
> > 'sysPicker/photoPicker',
> > 'sysPicker/appSelector',
> > 'sysPicker/navigation',
> > 'sysPicker/photoEditor',
> > 'photoEditor',
> > 'sysPicker/filePicker',
> > 'sysPicker/audioPicker',
> > 'sys/visualExtension',
> > 'sys/commonUI',
> > 'fileAccess',
> > 'autoFill/smart',
> > 'liveViewLockScreen',
> > 'recentPhoto'
> > ]
> > },
> > message: 'must be equal to one of the allowed values',
> > location: 'C:/Users/57357/Desktop/ClashMeta-master/entry/src/main/module.json5:46:22'
> > }
> 
> > hvigor ERROR: BUILD FAILED in 199 ms
> > 提示要把    "extensionAbilities": [
> > {
> > "name": "ClashVpnAbility",
> > "srcEntry": "./ets/ipc/ClashVpnAbility.ets",
> > "type": "vpn"
> > },中的“vpn”换掉

你咋改的，我看不了图片不知道咋个改的

**Comment by 001SM** [comment]
> > > hvigor ERROR: Failed :entry:default@PreBuild...
> > > hvigor ERROR: Schema validate failed.
> > > Detail: Please check the following fields.
> > > {
> > > instancePath: 'module.extensionAbilities[0].type',
> > > keyword: 'enum',
> > > params: {
> > > allowedValues: [
> > > 'form',
> > > 'workScheduler',
> > > 'inputMethod',
> > > 'service',
> > > 'accessibility',
> > > 'dataShare',
> > > 'fileShare',
> > > 'staticSubscriber',
> > > 'wallpaper',
> > > 'backup',
> > > 'window',
> > > 'enterpriseAdmin',
> > > 'thumbnail',
> > > 'preview',
> > > 'print',
> > > 'share',
> > > 'push',
> > > 'driver',
> > > 'action',
> > > 'adsService',
> > > 'embeddedUI',
> > > 'insightIntentUI',
> > > 'autoFill/password',
> > > 'hms/account',
> > > 'appAccountAuthorization',
> > > 'ads',
> > > 'remoteNotification',
> > > 'remoteLocation',
> > > 'statusBarView',
> > > 'voip',
> > > 'accountLogout',
> > > 'sysDialog/userAuth',
> > > 'sysDialog/common',
> > > 'sysDialog/atomicServicePanel',
> > > 'sysDialog/power',
> > > 'sysDialog/meetimeCall',
> > > 'sysDialog/meetimeContact',
> > > 'sysDialog/meetimeMessage',
> > > 'sysDialog/print',
> > > 'sysPicker/mediaControl',
> > > 'sysPicker/share',
> > > 'sysPicker/meetimeContact',
> > > 'sysPicker/meetimeCallLog',
> > > 'sysPicker/photoPicker',
> > > 'sysPicker/appSelector',
> > > 'sysPicker/navigation',
> > > 'sysPicker/photoEditor',
> > > 'photoEditor',
> > > 'sysPicker/filePicker',
> > > 'sysPicker/audioPicker',
> > > 'sys/visualExtension',
> > > 'sys/commonUI',
> > > 'fileAccess',
> > > 'autoFill/smart',
> > > 'liveViewLockScreen',
> > > 'recentPhoto'
> > > ]
> > > },
> > > message: 'must be equal to one of the allowed values',
> > > location: 'C:/Users/57357/Desktop/ClashMeta-master/entry/src/main/module.json5:46:22'
> > > }
> > 
> > 
> > > hvigor ERROR: BUILD FAILED in 199 ms
> > > 提示要把    "extensionAbilities": [
> > > {
> > > "name": "ClashVpnAbility",
> > > "srcEntry": "./ets/ipc/ClashVpnAbility.ets",
> > > "type": "vpn"
> > > },中的“vpn”换掉
> 
> 你咋改的，我看不了图片不知道咋个改的

我也看不了图片 @likuai2010

**Comment by starslightbright** [comment]
我知道了，在ide安装目录\sdk\default\hms\toolchains\modules.json里面改

**Comment by zhisibi** [comment]
> 我知道了，在ide安装目录\sdk\default\hms\toolchains\modules.json里面改
具体怎么改 求指导！

**Comment by TokenW** [comment]
> 我知道了，在ide安装目录\sdk\default\hms\toolchains\modules.json里面改

按照此目录没找到modules.json文件呢
![image](https://github.com/user-attachments/assets/6ae5c9c1-5b3c-4e40-a0b1-024cdaccd7e3)

**Comment by ZhangEnlin** [comment]
> > 我知道了，在ide安装目录\sdk\default\hms\toolchains\modules.json里面改
> 
> 按照此目录没找到modules.json文件呢 ![image](https://private-user-images.githubusercontent.com/11486227/372849020-6ae5c9c1-5b3c-4e40-a0b1-024cdaccd7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjg4MjIsIm5iZiI6MTcyODM2ODUyMiwicGF0aCI6Ii8xMTQ4NjIyNy8zNzI4NDkwMjAtNmFlNWM5YzEtNWIzYy00ZTQwLWEwYjEtMDI0Y2RhY2NkN2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA2MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjIwYmRiYjllZmE4YjUwYjUwZjRmOGFiNmJlNmUyOWNkZTQ1MjU2MWYyYzAzMDk4ZmYwMzM2ZWMzODllNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6WrZl2sz1UZEj4qjuKxRD-zRhc7jPtu40e-tov4RLXo)

找到这个报错的地方，ctrl+鼠标左键点击`type`，跳转到另一个文件，直接编辑那个文件，在enum值里添加：`vpn`
"extensionAbilities": [
      {
        "name": "ClashVpnAbility",
        "srcEntry": "./ets/ipc/ClashVpnAbility.ets",
        "type": "vpn"
      },

**Comment by poorest1212** [comment]
sdk枚举自己添加……这个是啥骚操作啊
