### ISSUE TITLE
安装报错：9568344

### ISSUE THREAD

**Issue by ZhangEnlin** [likuai2010/ClashMeta#9]
拉代码使用自己的华为账号重新签名之后，编译安装HAP时提示“code:9568344 error: install parse profile prop check error”，怎么解决啊，我这么菜吗。
官方给的[文档](https://developer.huawei.com/consumer/cn/doc/harmonyos-faqs-V5/faqs-app-debugging-13-V5)不行呀，说重签名证书之后，指纹变了，新的指纹需要添加到设备内的白名单，但是设备没有root权限没法修改文件，大佬们是怎么安装的？

**Comment by zhumyww** [comment]
我理解应该是你的证书要包含你的测试设备UID

**Comment by ZhangEnlin** [comment]
我又手动申请了一个证书和profile并将profile的设备uid配置正确，在deveco重新签名，安装依然报这个错，我这个操作是你说的操作吗？

**Comment by ZhangEnlin** [comment]
> 我又手动申请了一个证书和profile并将profile的设备uid配置正确，在deveco重新签名，安装依然报这个错，我这个操作是你说的操作吗？

我好像知道我哪里错了，不是签名的问题，现在问题是我打的包只有13mb，安装之后添加配置就闪退，有什么头绪吗大佬...是不是缺了项目里什么第三方库没打进去啊...
